production:
  adapter: postgresql
  database: msf
  username: Your_User
  password: Your_Password
  host: localhost
  port: 5432
  pool: 10
  timeout: 5

development:
  adapter: postgresql 
  database: \"${POSTGRES_DB}\"
  username: \"${POSTGRES_USER}\"
  password: \"${POSTGRES_PASSWORD}\"
  host: Postgres.pagodo_and_proxychain_internal
  port: 5432
  pool: 5
  timeout: 5