production:
  adapter: postgresql
  database: msf_database
  username: postgres
  # password: password
  host: database
  port: 5432
  pool: 75
  timeout: 5

# development:
#   adapter: postgresql 
#   database: \"${POSTGRES_DB}\"
#   username: \"${POSTGRES_USER}\"
#   password: \"${POSTGRES_PASSWORD}\"
#   host: 172.25.0.2
#   port: 5432
#   pool: 5
#   timeout: 5